wildcat_content_role.settings:
  type: config_object
  label: 'Wildcat Content Role settings'
  mapping:
    content_editor:
      type: string
      label: 'ID of the content editor user role'
    content_manager:
      type: string
      label: 'ID of the content manager user role'
